let commands = ["Funny",
"memes",
"friends",
"Happy",
"Sad",
"Hilarious",
"Crazy",
"Angry",
"Donald+Trump",
"Vladmir+Putin",
"Obama",
"OMG",
"Cool",
"400+Error",
"cats",
"dogs",
"coding",
"typing",
"error+500",
"harry+potter",
"coders",
"the+simpsons",
"love",
"instagood",
"photooftheday",
"fashion",
"beautiful",
"cute",
"tbt",
"like4like",
"followme",
"picoftheday",
"follow",
"me",
"selfie",
"summer",
"art",
"instadaily",
"friends",
"repost",
"nature",
"girl",
"fun",
"style",
"smile",
"food",
"instalike",
"likeforlike",
"family",
"travel",
"fitness",
"igers",
"tagsforlikes",
"follow4follow",
"nofilter",
"life",
"beauty",
"amazing",
"instamood",
"instagram",
"photography",
"vscocam",
"sun",
"photo",
"music",
"beach",
"followforfollow",
"bestoftheday",
"sky",
"ootd",
"sunset",
"dog",
"vsco",
"l4l",
"makeup",
"f4f",
"foodporn",
"hair",
"pretty",
"swag",
"cat",
"model",
"motivation",
"girls",
"baby",
"party",
"cool",
"lol",
"gym",
"design",
"instapic",
"funny",
"healthy",
"night",
"tflers",
"yummy",
"flowers",
"lifestyle",
"hot",
"instafood",
"wedding",
"fit",
"handmade",
"black",
"pink",
"blue",
"work",
"workout",
"blackandwhite",
"drawing",
"inspiration",
"home",
"holiday",
"christmas",
"nyc",
"london",
"sea",
"instacool",
"goodmorning",
"iphoneonly"];
let request = new XMLHttpRequest();
function displayGIFNicely(apiData) {
    let newData = JSON.parse(apiData);
    
    let data = newData.data[0].embed_url;
    document.getElementById("gif-image").innerHTML =
        // "&lt;embed src='" + data +  "'&gt;";
        "<embed src='" + data +  "'>";
        
}
request.onreadystatechange = function() {
    if (this.readyState == 4 && this.status == 200) {
        displayGIFNicely(this.responseText);
        
    }
    else if (this.readyState == 4 && this.status == 404) {
        
    }
}
// API KEY USING RANDOM GENERATOR FOR SEARCHED GIFS
function GIF_api() {
    let search = commands[Math.floor(Math.random() * commands.length)]
    request.open("GET", "https://mboladop-give-a-gif.herokuapp.com/gifs/" + search);
    request.send();
    return false;
}

